// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: commands.proto

package messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FleetMoveCommand struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	FleetId             string                 `protobuf:"bytes,1,opt,name=fleet_id,json=fleetId,proto3" json:"fleet_id,omitempty"`                                       // ID of the fleet to move
	DestinationSystemId string                 `protobuf:"bytes,2,opt,name=destination_system_id,json=destinationSystemId,proto3" json:"destination_system_id,omitempty"` // ID of the destination star system
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *FleetMoveCommand) Reset() {
	*x = FleetMoveCommand{}
	mi := &file_commands_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FleetMoveCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FleetMoveCommand) ProtoMessage() {}

func (x *FleetMoveCommand) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FleetMoveCommand.ProtoReflect.Descriptor instead.
func (*FleetMoveCommand) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{0}
}

func (x *FleetMoveCommand) GetFleetId() string {
	if x != nil {
		return x.FleetId
	}
	return ""
}

func (x *FleetMoveCommand) GetDestinationSystemId() string {
	if x != nil {
		return x.DestinationSystemId
	}
	return ""
}

type QueueConstructionCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColonyId      string                 `protobuf:"bytes,1,opt,name=colony_id,json=colonyId,proto3" json:"colony_id,omitempty"`             // ID of the colony where construction is queued
	BuildingType  string                 `protobuf:"bytes,2,opt,name=building_type,json=buildingType,proto3" json:"building_type,omitempty"` // Type of building to construct
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueConstructionCommand) Reset() {
	*x = QueueConstructionCommand{}
	mi := &file_commands_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueConstructionCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueConstructionCommand) ProtoMessage() {}

func (x *QueueConstructionCommand) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueConstructionCommand.ProtoReflect.Descriptor instead.
func (*QueueConstructionCommand) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{1}
}

func (x *QueueConstructionCommand) GetColonyId() string {
	if x != nil {
		return x.ColonyId
	}
	return ""
}

func (x *QueueConstructionCommand) GetBuildingType() string {
	if x != nil {
		return x.BuildingType
	}
	return ""
}

type QueueFleetConstructionCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StarbaseId    string                 `protobuf:"bytes,1,opt,name=starbase_id,json=starbaseId,proto3" json:"starbase_id,omitempty"` // ID of the starbase where fleet construction is queued
	FleetType     string                 `protobuf:"bytes,2,opt,name=fleet_type,json=fleetType,proto3" json:"fleet_type,omitempty"`    // Type of fleet to construct
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueFleetConstructionCommand) Reset() {
	*x = QueueFleetConstructionCommand{}
	mi := &file_commands_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueFleetConstructionCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueFleetConstructionCommand) ProtoMessage() {}

func (x *QueueFleetConstructionCommand) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueFleetConstructionCommand.ProtoReflect.Descriptor instead.
func (*QueueFleetConstructionCommand) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{2}
}

func (x *QueueFleetConstructionCommand) GetStarbaseId() string {
	if x != nil {
		return x.StarbaseId
	}
	return ""
}

func (x *QueueFleetConstructionCommand) GetFleetType() string {
	if x != nil {
		return x.FleetType
	}
	return ""
}

var File_commands_proto protoreflect.FileDescriptor

const file_commands_proto_rawDesc = "" +
	"\n" +
	"\x0ecommands.proto\x12\bmessages\"a\n" +
	"\x10FleetMoveCommand\x12\x19\n" +
	"\bfleet_id\x18\x01 \x01(\tR\afleetId\x122\n" +
	"\x15destination_system_id\x18\x02 \x01(\tR\x13destinationSystemId\"\\\n" +
	"\x18QueueConstructionCommand\x12\x1b\n" +
	"\tcolony_id\x18\x01 \x01(\tR\bcolonyId\x12#\n" +
	"\rbuilding_type\x18\x02 \x01(\tR\fbuildingType\"_\n" +
	"\x1dQueueFleetConstructionCommand\x12\x1f\n" +
	"\vstarbase_id\x18\x01 \x01(\tR\n" +
	"starbaseId\x12\x1d\n" +
	"\n" +
	"fleet_type\x18\x02 \x01(\tR\tfleetTypeB\x0eZ\fpkg/messagesb\x06proto3"

var (
	file_commands_proto_rawDescOnce sync.Once
	file_commands_proto_rawDescData []byte
)

func file_commands_proto_rawDescGZIP() []byte {
	file_commands_proto_rawDescOnce.Do(func() {
		file_commands_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_commands_proto_rawDesc), len(file_commands_proto_rawDesc)))
	})
	return file_commands_proto_rawDescData
}

var file_commands_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_commands_proto_goTypes = []any{
	(*FleetMoveCommand)(nil),              // 0: messages.FleetMoveCommand
	(*QueueConstructionCommand)(nil),      // 1: messages.QueueConstructionCommand
	(*QueueFleetConstructionCommand)(nil), // 2: messages.QueueFleetConstructionCommand
}
var file_commands_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_commands_proto_init() }
func file_commands_proto_init() {
	if File_commands_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_commands_proto_rawDesc), len(file_commands_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_commands_proto_goTypes,
		DependencyIndexes: file_commands_proto_depIdxs,
		MessageInfos:      file_commands_proto_msgTypes,
	}.Build()
	File_commands_proto = out.File
	file_commands_proto_goTypes = nil
	file_commands_proto_depIdxs = nil
}
