// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: galaxy.proto

package messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Galaxy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	StarSystems   []*StarSystem          `protobuf:"bytes,3,rep,name=starSystems,proto3" json:"starSystems,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Galaxy) Reset() {
	*x = Galaxy{}
	mi := &file_galaxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Galaxy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Galaxy) ProtoMessage() {}

func (x *Galaxy) ProtoReflect() protoreflect.Message {
	mi := &file_galaxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Galaxy.ProtoReflect.Descriptor instead.
func (*Galaxy) Descriptor() ([]byte, []int) {
	return file_galaxy_proto_rawDescGZIP(), []int{0}
}

func (x *Galaxy) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Galaxy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Galaxy) GetStarSystems() []*StarSystem {
	if x != nil {
		return x.StarSystems
	}
	return nil
}

type StarSystem struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OwnerId          string                 `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"` // ID of the owner empire
	LocationX        float64                `protobuf:"fixed64,4,opt,name=locationX,proto3" json:"locationX,omitempty"`
	LocationY        float64                `protobuf:"fixed64,5,opt,name=locationY,proto3" json:"locationY,omitempty"`
	ConnectedSystems []string               `protobuf:"bytes,6,rep,name=connectedSystems,proto3" json:"connectedSystems,omitempty"` // IDs of neighboring star systems
	Stars            []*Star                `protobuf:"bytes,7,rep,name=stars,proto3" json:"stars,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StarSystem) Reset() {
	*x = StarSystem{}
	mi := &file_galaxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StarSystem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StarSystem) ProtoMessage() {}

func (x *StarSystem) ProtoReflect() protoreflect.Message {
	mi := &file_galaxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StarSystem.ProtoReflect.Descriptor instead.
func (*StarSystem) Descriptor() ([]byte, []int) {
	return file_galaxy_proto_rawDescGZIP(), []int{1}
}

func (x *StarSystem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StarSystem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StarSystem) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *StarSystem) GetLocationX() float64 {
	if x != nil {
		return x.LocationX
	}
	return 0
}

func (x *StarSystem) GetLocationY() float64 {
	if x != nil {
		return x.LocationY
	}
	return 0
}

func (x *StarSystem) GetConnectedSystems() []string {
	if x != nil {
		return x.ConnectedSystems
	}
	return nil
}

func (x *StarSystem) GetStars() []*Star {
	if x != nil {
		return x.Stars
	}
	return nil
}

type Star struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Planets       []*Planet              `protobuf:"bytes,4,rep,name=planets,proto3" json:"planets,omitempty"`
	Size          float64                `protobuf:"fixed64,5,opt,name=size,proto3" json:"size,omitempty"` // Size of the star
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Star) Reset() {
	*x = Star{}
	mi := &file_galaxy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Star) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Star) ProtoMessage() {}

func (x *Star) ProtoReflect() protoreflect.Message {
	mi := &file_galaxy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Star.ProtoReflect.Descriptor instead.
func (*Star) Descriptor() ([]byte, []int) {
	return file_galaxy_proto_rawDescGZIP(), []int{2}
}

func (x *Star) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Star) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Star) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Star) GetPlanets() []*Planet {
	if x != nil {
		return x.Planets
	}
	return nil
}

func (x *Star) GetSize() float64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type Planet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`                // Size of the planet
	OrbitRadius   float64                `protobuf:"fixed64,4,opt,name=orbitRadius,proto3" json:"orbitRadius,omitempty"` // Distance from the star
	Angle         float64                `protobuf:"fixed64,5,opt,name=angle,proto3" json:"angle,omitempty"`             // Current angle in orbit
	Type          string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Planet) Reset() {
	*x = Planet{}
	mi := &file_galaxy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Planet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Planet) ProtoMessage() {}

func (x *Planet) ProtoReflect() protoreflect.Message {
	mi := &file_galaxy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Planet.ProtoReflect.Descriptor instead.
func (*Planet) Descriptor() ([]byte, []int) {
	return file_galaxy_proto_rawDescGZIP(), []int{3}
}

func (x *Planet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Planet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Planet) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Planet) GetOrbitRadius() float64 {
	if x != nil {
		return x.OrbitRadius
	}
	return 0
}

func (x *Planet) GetAngle() float64 {
	if x != nil {
		return x.Angle
	}
	return 0
}

func (x *Planet) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

var File_galaxy_proto protoreflect.FileDescriptor

const file_galaxy_proto_rawDesc = "" +
	"\n" +
	"\fgalaxy.proto\x12\bmessages\"d\n" +
	"\x06Galaxy\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x126\n" +
	"\vstarSystems\x18\x03 \x03(\v2\x14.messages.StarSystemR\vstarSystems\"\xd9\x01\n" +
	"\n" +
	"StarSystem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\tR\aownerId\x12\x1c\n" +
	"\tlocationX\x18\x04 \x01(\x01R\tlocationX\x12\x1c\n" +
	"\tlocationY\x18\x05 \x01(\x01R\tlocationY\x12*\n" +
	"\x10connectedSystems\x18\x06 \x03(\tR\x10connectedSystems\x12$\n" +
	"\x05stars\x18\a \x03(\v2\x0e.messages.StarR\x05stars\"~\n" +
	"\x04Star\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12*\n" +
	"\aplanets\x18\x04 \x03(\v2\x10.messages.PlanetR\aplanets\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x01R\x04size\"\x8c\x01\n" +
	"\x06Planet\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\x12 \n" +
	"\vorbitRadius\x18\x04 \x01(\x01R\vorbitRadius\x12\x14\n" +
	"\x05angle\x18\x05 \x01(\x01R\x05angle\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04typeB\x0eZ\fpkg/messagesb\x06proto3"

var (
	file_galaxy_proto_rawDescOnce sync.Once
	file_galaxy_proto_rawDescData []byte
)

func file_galaxy_proto_rawDescGZIP() []byte {
	file_galaxy_proto_rawDescOnce.Do(func() {
		file_galaxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_galaxy_proto_rawDesc), len(file_galaxy_proto_rawDesc)))
	})
	return file_galaxy_proto_rawDescData
}

var file_galaxy_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_galaxy_proto_goTypes = []any{
	(*Galaxy)(nil),     // 0: messages.Galaxy
	(*StarSystem)(nil), // 1: messages.StarSystem
	(*Star)(nil),       // 2: messages.Star
	(*Planet)(nil),     // 3: messages.Planet
}
var file_galaxy_proto_depIdxs = []int32{
	1, // 0: messages.Galaxy.starSystems:type_name -> messages.StarSystem
	2, // 1: messages.StarSystem.stars:type_name -> messages.Star
	3, // 2: messages.Star.planets:type_name -> messages.Planet
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_galaxy_proto_init() }
func file_galaxy_proto_init() {
	if File_galaxy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_galaxy_proto_rawDesc), len(file_galaxy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_galaxy_proto_goTypes,
		DependencyIndexes: file_galaxy_proto_depIdxs,
		MessageInfos:      file_galaxy_proto_msgTypes,
	}.Build()
	File_galaxy_proto = out.File
	file_galaxy_proto_goTypes = nil
	file_galaxy_proto_depIdxs = nil
}
