// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: messages.proto

package messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GameMessage struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	MessageId    string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"` // Unique identifier for the message
	GameId       string                 `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`          // ID of the game this message belongs to
	PlayerId     string                 `protobuf:"bytes,3,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`    // ID of the player sending the packet
	Timestamp    int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SessionToken string                 `protobuf:"bytes,5,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"` // Unique session identifier for the connection
	// Types that are valid to be assigned to Content:
	//
	//	*GameMessage_ChatMessage
	//	*GameMessage_PlayerCommand
	//	*GameMessage_GameStateUpdate
	Content       isGameMessage_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameMessage) Reset() {
	*x = GameMessage{}
	mi := &file_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameMessage) ProtoMessage() {}

func (x *GameMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameMessage.ProtoReflect.Descriptor instead.
func (*GameMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

func (x *GameMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *GameMessage) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *GameMessage) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *GameMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *GameMessage) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *GameMessage) GetContent() isGameMessage_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *GameMessage) GetChatMessage() *ChatMessage {
	if x != nil {
		if x, ok := x.Content.(*GameMessage_ChatMessage); ok {
			return x.ChatMessage
		}
	}
	return nil
}

func (x *GameMessage) GetPlayerCommand() *PlayerCommand {
	if x != nil {
		if x, ok := x.Content.(*GameMessage_PlayerCommand); ok {
			return x.PlayerCommand
		}
	}
	return nil
}

func (x *GameMessage) GetGameStateUpdate() *GameStateUpdate {
	if x != nil {
		if x, ok := x.Content.(*GameMessage_GameStateUpdate); ok {
			return x.GameStateUpdate
		}
	}
	return nil
}

type isGameMessage_Content interface {
	isGameMessage_Content()
}

type GameMessage_ChatMessage struct {
	ChatMessage *ChatMessage `protobuf:"bytes,6,opt,name=chat_message,json=chatMessage,proto3,oneof"` // Chat message sent by the player
}

type GameMessage_PlayerCommand struct {
	PlayerCommand *PlayerCommand `protobuf:"bytes,7,opt,name=player_command,json=playerCommand,proto3,oneof"` // Command issued by the player
}

type GameMessage_GameStateUpdate struct {
	GameStateUpdate *GameStateUpdate `protobuf:"bytes,8,opt,name=game_state_update,json=gameStateUpdate,proto3,oneof"` // Update to the game state
}

func (*GameMessage_ChatMessage) isGameMessage_Content() {}

func (*GameMessage_PlayerCommand) isGameMessage_Content() {}

func (*GameMessage_GameStateUpdate) isGameMessage_Content() {}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // The chat message content
	Channel       string                 `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"` // The channel or room where the message is sent
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

func (x *ChatMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatMessage) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

type PlayerCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Command:
	//
	//	*PlayerCommand_FleetMoveCommand
	//	*PlayerCommand_QueueConstructionCommand
	//	*PlayerCommand_QueueFleetConstructionCommand
	Command       isPlayerCommand_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerCommand) Reset() {
	*x = PlayerCommand{}
	mi := &file_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerCommand) ProtoMessage() {}

func (x *PlayerCommand) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerCommand.ProtoReflect.Descriptor instead.
func (*PlayerCommand) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerCommand) GetCommand() isPlayerCommand_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *PlayerCommand) GetFleetMoveCommand() *FleetMoveCommand {
	if x != nil {
		if x, ok := x.Command.(*PlayerCommand_FleetMoveCommand); ok {
			return x.FleetMoveCommand
		}
	}
	return nil
}

func (x *PlayerCommand) GetQueueConstructionCommand() *QueueConstructionCommand {
	if x != nil {
		if x, ok := x.Command.(*PlayerCommand_QueueConstructionCommand); ok {
			return x.QueueConstructionCommand
		}
	}
	return nil
}

func (x *PlayerCommand) GetQueueFleetConstructionCommand() *QueueFleetConstructionCommand {
	if x != nil {
		if x, ok := x.Command.(*PlayerCommand_QueueFleetConstructionCommand); ok {
			return x.QueueFleetConstructionCommand
		}
	}
	return nil
}

type isPlayerCommand_Command interface {
	isPlayerCommand_Command()
}

type PlayerCommand_FleetMoveCommand struct {
	FleetMoveCommand *FleetMoveCommand `protobuf:"bytes,1,opt,name=fleet_move_command,json=fleetMoveCommand,proto3,oneof"` // Command to move a fleet
}

type PlayerCommand_QueueConstructionCommand struct {
	QueueConstructionCommand *QueueConstructionCommand `protobuf:"bytes,2,opt,name=queue_construction_command,json=queueConstructionCommand,proto3,oneof"` // Command to queue a construction
}

type PlayerCommand_QueueFleetConstructionCommand struct {
	QueueFleetConstructionCommand *QueueFleetConstructionCommand `protobuf:"bytes,3,opt,name=queue_fleet_construction_command,json=queueFleetConstructionCommand,proto3,oneof"` // Command to queue fleet construction
}

func (*PlayerCommand_FleetMoveCommand) isPlayerCommand_Command() {}

func (*PlayerCommand_QueueConstructionCommand) isPlayerCommand_Command() {}

func (*PlayerCommand_QueueFleetConstructionCommand) isPlayerCommand_Command() {}

type IdMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdMessage) Reset() {
	*x = IdMessage{}
	mi := &file_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdMessage) ProtoMessage() {}

func (x *IdMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdMessage.ProtoReflect.Descriptor instead.
func (*IdMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{3}
}

func (x *IdMessage) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_messages_proto protoreflect.FileDescriptor

const file_messages_proto_rawDesc = "" +
	"\n" +
	"\x0emessages.proto\x12\bmessages\x1a\x0ecommands.proto\x1a\x0fgamestate.proto\"\xf7\x02\n" +
	"\vGameMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\tR\x06gameId\x12\x1b\n" +
	"\tplayer_id\x18\x03 \x01(\tR\bplayerId\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12#\n" +
	"\rsession_token\x18\x05 \x01(\tR\fsessionToken\x12:\n" +
	"\fchat_message\x18\x06 \x01(\v2\x15.messages.ChatMessageH\x00R\vchatMessage\x12@\n" +
	"\x0eplayer_command\x18\a \x01(\v2\x17.messages.PlayerCommandH\x00R\rplayerCommand\x12G\n" +
	"\x11game_state_update\x18\b \x01(\v2\x19.messages.GameStateUpdateH\x00R\x0fgameStateUpdateB\t\n" +
	"\acontent\"A\n" +
	"\vChatMessage\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\achannel\x18\x02 \x01(\tR\achannel\"\xbe\x02\n" +
	"\rPlayerCommand\x12J\n" +
	"\x12fleet_move_command\x18\x01 \x01(\v2\x1a.messages.FleetMoveCommandH\x00R\x10fleetMoveCommand\x12b\n" +
	"\x1aqueue_construction_command\x18\x02 \x01(\v2\".messages.QueueConstructionCommandH\x00R\x18queueConstructionCommand\x12r\n" +
	" queue_fleet_construction_command\x18\x03 \x01(\v2'.messages.QueueFleetConstructionCommandH\x00R\x1dqueueFleetConstructionCommandB\t\n" +
	"\acommand\"\x1b\n" +
	"\tIdMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02idB\x0eZ\fpkg/messagesb\x06proto3"

var (
	file_messages_proto_rawDescOnce sync.Once
	file_messages_proto_rawDescData []byte
)

func file_messages_proto_rawDescGZIP() []byte {
	file_messages_proto_rawDescOnce.Do(func() {
		file_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)))
	})
	return file_messages_proto_rawDescData
}

var file_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_messages_proto_goTypes = []any{
	(*GameMessage)(nil),                   // 0: messages.GameMessage
	(*ChatMessage)(nil),                   // 1: messages.ChatMessage
	(*PlayerCommand)(nil),                 // 2: messages.PlayerCommand
	(*IdMessage)(nil),                     // 3: messages.IdMessage
	(*GameStateUpdate)(nil),               // 4: messages.GameStateUpdate
	(*FleetMoveCommand)(nil),              // 5: messages.FleetMoveCommand
	(*QueueConstructionCommand)(nil),      // 6: messages.QueueConstructionCommand
	(*QueueFleetConstructionCommand)(nil), // 7: messages.QueueFleetConstructionCommand
}
var file_messages_proto_depIdxs = []int32{
	1, // 0: messages.GameMessage.chat_message:type_name -> messages.ChatMessage
	2, // 1: messages.GameMessage.player_command:type_name -> messages.PlayerCommand
	4, // 2: messages.GameMessage.game_state_update:type_name -> messages.GameStateUpdate
	5, // 3: messages.PlayerCommand.fleet_move_command:type_name -> messages.FleetMoveCommand
	6, // 4: messages.PlayerCommand.queue_construction_command:type_name -> messages.QueueConstructionCommand
	7, // 5: messages.PlayerCommand.queue_fleet_construction_command:type_name -> messages.QueueFleetConstructionCommand
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_messages_proto_init() }
func file_messages_proto_init() {
	if File_messages_proto != nil {
		return
	}
	file_commands_proto_init()
	file_gamestate_proto_init()
	file_messages_proto_msgTypes[0].OneofWrappers = []any{
		(*GameMessage_ChatMessage)(nil),
		(*GameMessage_PlayerCommand)(nil),
		(*GameMessage_GameStateUpdate)(nil),
	}
	file_messages_proto_msgTypes[2].OneofWrappers = []any{
		(*PlayerCommand_FleetMoveCommand)(nil),
		(*PlayerCommand_QueueConstructionCommand)(nil),
		(*PlayerCommand_QueueFleetConstructionCommand)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_proto_goTypes,
		DependencyIndexes: file_messages_proto_depIdxs,
		MessageInfos:      file_messages_proto_msgTypes,
	}.Build()
	File_messages_proto = out.File
	file_messages_proto_goTypes = nil
	file_messages_proto_depIdxs = nil
}
