// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.31.1
// source: messages.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { FleetMoveCommand, QueueConstructionCommand, QueueFleetConstructionCommand } from "./commands";
import { GameStateUpdate } from "./gamestate";

export const protobufPackage = "messages";

export interface GameMessage {
  /** Unique identifier for the message */
  messageId: string;
  /** ID of the game this message belongs to */
  gameId: string;
  /** ID of the player sending the packet */
  playerId: string;
  timestamp: number;
  /** Unique session identifier for the connection */
  sessionToken: string;
  /** Chat message sent by the player */
  chatMessage?:
    | ChatMessage
    | undefined;
  /** Command issued by the player */
  playerCommand?:
    | PlayerCommand
    | undefined;
  /** Update to the game state */
  gameStateUpdate?: GameStateUpdate | undefined;
}

export interface ChatMessage {
  /** The chat message content */
  message: string;
  /** The channel or room where the message is sent */
  channel: string;
}

export interface PlayerCommand {
  /** Command to move a fleet */
  fleetMoveCommand?:
    | FleetMoveCommand
    | undefined;
  /** Command to queue a construction */
  queueConstructionCommand?:
    | QueueConstructionCommand
    | undefined;
  /** Command to queue fleet construction */
  queueFleetConstructionCommand?: QueueFleetConstructionCommand | undefined;
}

export interface IdMessage {
  id: number;
}

function createBaseGameMessage(): GameMessage {
  return {
    messageId: "",
    gameId: "",
    playerId: "",
    timestamp: 0,
    sessionToken: "",
    chatMessage: undefined,
    playerCommand: undefined,
    gameStateUpdate: undefined,
  };
}

export const GameMessage: MessageFns<GameMessage> = {
  encode(message: GameMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.messageId !== "") {
      writer.uint32(10).string(message.messageId);
    }
    if (message.gameId !== "") {
      writer.uint32(18).string(message.gameId);
    }
    if (message.playerId !== "") {
      writer.uint32(26).string(message.playerId);
    }
    if (message.timestamp !== 0) {
      writer.uint32(32).int64(message.timestamp);
    }
    if (message.sessionToken !== "") {
      writer.uint32(42).string(message.sessionToken);
    }
    if (message.chatMessage !== undefined) {
      ChatMessage.encode(message.chatMessage, writer.uint32(50).fork()).join();
    }
    if (message.playerCommand !== undefined) {
      PlayerCommand.encode(message.playerCommand, writer.uint32(58).fork()).join();
    }
    if (message.gameStateUpdate !== undefined) {
      GameStateUpdate.encode(message.gameStateUpdate, writer.uint32(66).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GameMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGameMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.messageId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.gameId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.playerId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.timestamp = longToNumber(reader.int64());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.sessionToken = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.chatMessage = ChatMessage.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.playerCommand = PlayerCommand.decode(reader, reader.uint32());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.gameStateUpdate = GameStateUpdate.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GameMessage {
    return {
      messageId: isSet(object.messageId) ? globalThis.String(object.messageId) : "",
      gameId: isSet(object.gameId) ? globalThis.String(object.gameId) : "",
      playerId: isSet(object.playerId) ? globalThis.String(object.playerId) : "",
      timestamp: isSet(object.timestamp) ? globalThis.Number(object.timestamp) : 0,
      sessionToken: isSet(object.sessionToken) ? globalThis.String(object.sessionToken) : "",
      chatMessage: isSet(object.chatMessage) ? ChatMessage.fromJSON(object.chatMessage) : undefined,
      playerCommand: isSet(object.playerCommand) ? PlayerCommand.fromJSON(object.playerCommand) : undefined,
      gameStateUpdate: isSet(object.gameStateUpdate) ? GameStateUpdate.fromJSON(object.gameStateUpdate) : undefined,
    };
  },

  toJSON(message: GameMessage): unknown {
    const obj: any = {};
    if (message.messageId !== "") {
      obj.messageId = message.messageId;
    }
    if (message.gameId !== "") {
      obj.gameId = message.gameId;
    }
    if (message.playerId !== "") {
      obj.playerId = message.playerId;
    }
    if (message.timestamp !== 0) {
      obj.timestamp = Math.round(message.timestamp);
    }
    if (message.sessionToken !== "") {
      obj.sessionToken = message.sessionToken;
    }
    if (message.chatMessage !== undefined) {
      obj.chatMessage = ChatMessage.toJSON(message.chatMessage);
    }
    if (message.playerCommand !== undefined) {
      obj.playerCommand = PlayerCommand.toJSON(message.playerCommand);
    }
    if (message.gameStateUpdate !== undefined) {
      obj.gameStateUpdate = GameStateUpdate.toJSON(message.gameStateUpdate);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GameMessage>, I>>(base?: I): GameMessage {
    return GameMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GameMessage>, I>>(object: I): GameMessage {
    const message = createBaseGameMessage();
    message.messageId = object.messageId ?? "";
    message.gameId = object.gameId ?? "";
    message.playerId = object.playerId ?? "";
    message.timestamp = object.timestamp ?? 0;
    message.sessionToken = object.sessionToken ?? "";
    message.chatMessage = (object.chatMessage !== undefined && object.chatMessage !== null)
      ? ChatMessage.fromPartial(object.chatMessage)
      : undefined;
    message.playerCommand = (object.playerCommand !== undefined && object.playerCommand !== null)
      ? PlayerCommand.fromPartial(object.playerCommand)
      : undefined;
    message.gameStateUpdate = (object.gameStateUpdate !== undefined && object.gameStateUpdate !== null)
      ? GameStateUpdate.fromPartial(object.gameStateUpdate)
      : undefined;
    return message;
  },
};

function createBaseChatMessage(): ChatMessage {
  return { message: "", channel: "" };
}

export const ChatMessage: MessageFns<ChatMessage> = {
  encode(message: ChatMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.message !== "") {
      writer.uint32(10).string(message.message);
    }
    if (message.channel !== "") {
      writer.uint32(18).string(message.channel);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChatMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChatMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.channel = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ChatMessage {
    return {
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      channel: isSet(object.channel) ? globalThis.String(object.channel) : "",
    };
  },

  toJSON(message: ChatMessage): unknown {
    const obj: any = {};
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.channel !== "") {
      obj.channel = message.channel;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ChatMessage>, I>>(base?: I): ChatMessage {
    return ChatMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChatMessage>, I>>(object: I): ChatMessage {
    const message = createBaseChatMessage();
    message.message = object.message ?? "";
    message.channel = object.channel ?? "";
    return message;
  },
};

function createBasePlayerCommand(): PlayerCommand {
  return { fleetMoveCommand: undefined, queueConstructionCommand: undefined, queueFleetConstructionCommand: undefined };
}

export const PlayerCommand: MessageFns<PlayerCommand> = {
  encode(message: PlayerCommand, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.fleetMoveCommand !== undefined) {
      FleetMoveCommand.encode(message.fleetMoveCommand, writer.uint32(10).fork()).join();
    }
    if (message.queueConstructionCommand !== undefined) {
      QueueConstructionCommand.encode(message.queueConstructionCommand, writer.uint32(18).fork()).join();
    }
    if (message.queueFleetConstructionCommand !== undefined) {
      QueueFleetConstructionCommand.encode(message.queueFleetConstructionCommand, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PlayerCommand {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePlayerCommand();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.fleetMoveCommand = FleetMoveCommand.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.queueConstructionCommand = QueueConstructionCommand.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.queueFleetConstructionCommand = QueueFleetConstructionCommand.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PlayerCommand {
    return {
      fleetMoveCommand: isSet(object.fleetMoveCommand) ? FleetMoveCommand.fromJSON(object.fleetMoveCommand) : undefined,
      queueConstructionCommand: isSet(object.queueConstructionCommand)
        ? QueueConstructionCommand.fromJSON(object.queueConstructionCommand)
        : undefined,
      queueFleetConstructionCommand: isSet(object.queueFleetConstructionCommand)
        ? QueueFleetConstructionCommand.fromJSON(object.queueFleetConstructionCommand)
        : undefined,
    };
  },

  toJSON(message: PlayerCommand): unknown {
    const obj: any = {};
    if (message.fleetMoveCommand !== undefined) {
      obj.fleetMoveCommand = FleetMoveCommand.toJSON(message.fleetMoveCommand);
    }
    if (message.queueConstructionCommand !== undefined) {
      obj.queueConstructionCommand = QueueConstructionCommand.toJSON(message.queueConstructionCommand);
    }
    if (message.queueFleetConstructionCommand !== undefined) {
      obj.queueFleetConstructionCommand = QueueFleetConstructionCommand.toJSON(message.queueFleetConstructionCommand);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PlayerCommand>, I>>(base?: I): PlayerCommand {
    return PlayerCommand.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PlayerCommand>, I>>(object: I): PlayerCommand {
    const message = createBasePlayerCommand();
    message.fleetMoveCommand = (object.fleetMoveCommand !== undefined && object.fleetMoveCommand !== null)
      ? FleetMoveCommand.fromPartial(object.fleetMoveCommand)
      : undefined;
    message.queueConstructionCommand =
      (object.queueConstructionCommand !== undefined && object.queueConstructionCommand !== null)
        ? QueueConstructionCommand.fromPartial(object.queueConstructionCommand)
        : undefined;
    message.queueFleetConstructionCommand =
      (object.queueFleetConstructionCommand !== undefined && object.queueFleetConstructionCommand !== null)
        ? QueueFleetConstructionCommand.fromPartial(object.queueFleetConstructionCommand)
        : undefined;
    return message;
  },
};

function createBaseIdMessage(): IdMessage {
  return { id: 0 };
}

export const IdMessage: MessageFns<IdMessage> = {
  encode(message: IdMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint64(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): IdMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseIdMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): IdMessage {
    return { id: isSet(object.id) ? globalThis.Number(object.id) : 0 };
  },

  toJSON(message: IdMessage): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<IdMessage>, I>>(base?: I): IdMessage {
    return IdMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<IdMessage>, I>>(object: I): IdMessage {
    const message = createBaseIdMessage();
    message.id = object.id ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
